name: CI/CD - QA

on:
  push:
    branches: [qa]
  pull_request:
    branches: [qa]

jobs:
  test-and-deploy-qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run full test suite
        run: pytest tests/

      - name: Deploy to QA Databricks workspace
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_QA }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_QA }}
        run: |
          databricks configure --token <<EOF
          $DATABRICKS_HOST
          $DATABRICKS_TOKEN
          EOF
          databricks workspace import_dir ./notebooks /Workspace/QA --overwrite
